steps:
  # Step 1: Install Terraform
  - name: 'hashicorp/terraform:latest'
    id: 'Install Terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform --version

  # Step 2: Initialize Terraform
  - name: 'hashicorp/terraform:latest'
    id: 'Terraform Init'
    entrypoint: 'sh'
    args:
      - '-c'
      - |        
        terraform init
        
  # Step 3: Validate Terraform
  - name: 'hashicorp/terraform:latest'
    id: 'Terraform Validate'
    entrypoint: 'sh'
    args:
      - '-c'
      - |        
        terraform fmt

  # Step 4: Terraform Plan (Optional, for dry-run)
  - name: 'hashicorp/terraform:latest'
    id: 'Terraform Plan'
    entrypoint: 'sh'
    args:
      - '-c'
      - |   
        terraform plan
     env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.TF_API_TOKEN }}

  # Step 5: Terraform Apply
  - name: 'hashicorp/terraform:latest'
    id: 'Terraform Apply'
    entrypoint: 'sh'
    args:
      - '-c'
      - |  
        terraform apply -auto-approve
    env:
       GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.TF_API_TOKEN }}
options:
   logging: CLOUD_LOGGING_ONLY
   default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET


